# Generated by Django 4.2.30 on 2026-06-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0004_alter_shippingmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingrate",
            name="weight_max",
            field=models.DecimalField(
                decimal_places=3,
                default=9999,
                max_digits=8,
                verbose_name="حداکثر وزن (kg)",
            ),
        ),
    ]
