# Generated by Django 4.2.30 on 2026-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0005_fix_weight_max_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="province",
            name="zone_number",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Zone 1 — همان استان (خراسان رضوی)"),
                    (2, "Zone 2 — استان\u200cهای همجوار"),
                    (3, "Zone 3 — سایر استان\u200cها"),
                ],
                default=3,
                help_text="Zone 1: خراسان رضوی، Zone 2: همجوار، Zone 3: سایر",
                verbose_name="شماره منطقه (Zone)",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="fixed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="فقط برای پیک — قیمت ثابت بدون وابستگی به وزن",
                max_digits=12,
                null=True,
                verbose_name="قیمت ثابت (پیک)",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("pishtaz", "پست پیشتاز"),
                    ("sefareshi", "پست عادی/سفارشی"),
                    ("tipax", "تیپاکس"),
                    ("pik", "پیک (فقط مشهد)"),
                    ("barbari", "باربری"),
                ],
                default="pishtaz",
                max_length=20,
                verbose_name="نوع روش ارسال",
            ),
        ),
    ]
