# Generated by Django 4.2.30 on 2026-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_order_idempotency_key_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=8, verbose_name="ارتفاع (cm)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=8, verbose_name="طول (cm)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=8, verbose_name="عرض (cm)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=8, verbose_name="وزن واقعی (kg)"
            ),
        ),
    ]
