# Generated by Django 4.2.30 on 2026-06-22 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0012_add_zone_dimensions_method_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200, verbose_name="عنوان")),
                ("value", models.CharField(max_length=500, verbose_name="مقدار")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصات فنی",
                "verbose_name_plural": "مشخصات فنی",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="امتیاز (۱ تا ۵)"
                    ),
                ),
                ("text", models.TextField(verbose_name="متن نظر")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="تایید شده"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر کاربر",
                "verbose_name_plural": "نظرات کاربران",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="متن ویژگی")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی محصول",
                "verbose_name_plural": "ویژگی\u200cهای محصول",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="سوال")),
                ("answer", models.TextField(verbose_name="پاسخ")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال متداول",
                "verbose_name_plural": "سوالات متداول",
                "ordering": ["order"],
            },
        ),
    ]
