# Generated by Django 4.2.30 on 2026-06-18 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="کلید API پلتفرم میمو (Mimo Platform)",
                        max_length=256,
                        verbose_name="کلید API Mimo",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        default="https://api.mimo.org/v1",
                        help_text="آدرس پایه API میمو — بدون /chat/completions",
                        verbose_name="آدرس پایه API",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="mimo-v2.5-pro",
                        help_text="شناسه مدل Mimo (مثلاً mimo-v2.5-pro یا mimo-v2-flash)",
                        max_length=100,
                        verbose_name="مدل",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.7,
                        max_digits=3,
                        verbose_name="دما (Temperature)",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=1024, verbose_name="حداکثر توکن"
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        default="سلام! 👋 من دستیار فروش آتی فرزام هستم. چطور می\u200cتونم کمکتون کنم؟",
                        verbose_name="پیام خوش\u200cآمدگویی",
                    ),
                ),
                (
                    "quick_replies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='لیست دکمه\u200cها — مثال: ["مشاهده محصولات", "راهنمای خرید", "تماس با پشتیبانی"]',
                        verbose_name="پاسخ\u200cهای سریع",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="چت\u200cبات فعال"),
                ),
                (
                    "last_prompt_update",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین بروزرسانی پرامپت"
                    ),
                ),
                (
                    "cached_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="پرامپت کش\u200cشده",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تنظیمات چت\u200cبات",
                "verbose_name_plural": "تنظیمات چت\u200cبات",
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه گفتگو",
                "verbose_name_plural": "جلسات گفتگو",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "کاربر"), ("assistant", "دستیار")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام چت",
                "verbose_name_plural": "پیام\u200cهای چت",
                "ordering": ["created_at"],
            },
        ),
    ]
