# Generated by Django 4.2.30 on 2026-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_site_settings_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("image", models.ImageField(upload_to="banners/")),
                ("link", models.URLField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(allow_unicode=True, unique=True)),
                ("content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "صفحه",
                "verbose_name_plural": "صفحات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="partners/")),
                ("website", models.URLField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "شریک",
                "verbose_name_plural": "شرکا",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address",
            field=models.CharField(blank=True, default="تهران، ایران", max_length=500),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="app_store_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_play_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="software_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="software_login_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="support_email",
            field=models.EmailField(
                blank=True, default="info@atifarzam.ir", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="work_hours",
            field=models.CharField(
                blank=True, default="شنبه تا چهارشنبه — ۸ تا ۱۷", max_length=200
            ),
        ),
    ]
