# Generated by Django 4.2.30 on 2026-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_banner_page_partner_sitesettings_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/about/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="app_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/app/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="category_image_1",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/categories/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="category_image_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/categories/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="category_image_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/categories/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="category_image_4",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/categories/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_bg_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/hero/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="newsletter_bg",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/newsletter/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="software_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/software/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_bg",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/testimonials/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="why_us_icon_1",
            field=models.ImageField(blank=True, null=True, upload_to="site/why_us/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="why_us_icon_2",
            field=models.ImageField(blank=True, null=True, upload_to="site/why_us/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="why_us_icon_3",
            field=models.ImageField(blank=True, null=True, upload_to="site/why_us/"),
        ),
    ]
