# Generated by Django 4.2.30 on 2026-06-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_site_settings_image_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="cta2_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="cta2_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="banner",
            name="cta_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="cta_text",
            field=models.CharField(blank=True, default="مشاهده", max_length=100),
        ),
    ]
