# Generated by Django 4.2.30 on 2026-06-17 08:25

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    table_name = "core_sitesettings"
    with schema_editor.connection.cursor() as cursor:
        columns = [
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        ]
        if "otp_test_mode" not in columns:
            cursor.execute(
                'ALTER TABLE "core_sitesettings" ADD COLUMN "otp_test_mode" boolean NOT NULL DEFAULT false'
            )
        if "shop_enabled" not in columns:
            cursor.execute(
                'ALTER TABLE "core_sitesettings" ADD COLUMN "shop_enabled" boolean NOT NULL DEFAULT true'
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_contactmessage_sitesettings_shop_enabled"),
    ]

    operations = [
        migrations.RunPython(add_fields_if_not_exist, migrations.RunPython.noop),
    ]
