# Generated by Django 4.2.30 on 2026-06-17 08:25

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    table_name = SiteSettings._meta.db_table
    columns = [col.name for col in schema_editor.connection.introspection.get_table_description(schema_editor.cursor, table_name)]
    with schema_editor.connection.cursor() as cursor:
        if "otp_test_mode" not in columns:
            schema_editor.add_field(SiteSettings, SiteSettings._meta.get_field("otp_test_mode"))
        if "shop_enabled" not in columns:
            schema_editor.add_field(SiteSettings, SiteSettings._meta.get_field("shop_enabled"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_contactmessage_sitesettings_shop_enabled"),
    ]

    operations = [
        migrations.RunPython(add_fields_if_not_exist, migrations.RunPython.noop),
    ]
