# Generated by Django 4.2.30 on 2026-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_contactmessage_sitesettings_shop_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="otp_test_mode",
            field=models.BooleanField(
                default=False, verbose_name="حالت تست پیامک (نمایش کد در فرانت)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shop_enabled",
            field=models.BooleanField(default=True, verbose_name="فروشگاه فعال"),
        ),
    ]
