services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://95.38.161.104
        NEXT_PUBLIC_SITE_URL: http://95.38.161.205
        INTERNAL_API_URL: http://95.38.161.104
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://95.38.161.104
      NEXT_PUBLIC_SITE_URL: http://95.38.161.205
      INTERNAL_API_URL: http://95.38.161.104

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
